version: 0.1

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "📦 [Install Phase] 의존성 설치 시작"
      - chmod +x ./gradlew
      - echo "✅ [Install Phase] 완료"

  build:
    commands:
      - echo "🚀 [Build Phase] Gradle 빌드 시작"
      - ./gradlew clean build -x test
      - echo "✅ [Build Phase] 빌드 성공"

  post_build:
    commands:
      - echo "📤 [Post Build Phase] 산출물 패키징 시작"
      - BUILD_JAR=$(find build/libs -name "*.jar" -not -name "*plain.jar" | head -n 1)
      - echo "📌 Build JAR located at - $BUILD_JAR"
      - mkdir -p infra/output
      - cp "$BUILD_JAR" infra/output/
      - cp infra/deploy.sh infra/output/
      - cp infra/appspec.yml ../appspec.yml
      - echo "✅ [Post Build Phase] 완료"

artifacts:
  files:
    - backend/infra/output/**/*
    - appspec.yml
